# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

olitaz-home:
    resource: "@OlitazHomeBundle/Resources/config/routing.yml"
