# DefaultController
OlitazHomeBundle_homepage:
    pattern:  /
    defaults: { _controller: OlitazHomeBundle:Default:index }
OlitazHomeBundle_legal_notices:
    pattern:  /mentions-legales
    defaults: { _controller: OlitazHomeBundle:Default:legalNotices }

# PresentationController
OlitazHomeBundle_presentation:
    pattern:  /presentation
    defaults: { _controller: OlitazHomeBundle:Presentation:presentation }
OlitazHomeBundle_prestations:
    pattern:  /prestations
    defaults: { _controller: OlitazHomeBundle:Presentation:prestations }
OlitazHomeBundle_audit:
    pattern:  /prestations/audit-conseil
    defaults: { _controller: OlitazHomeBundle:Presentation:audit }
OlitazHomeBundle_development:
    pattern:  /prestations/developpement-specifique
    defaults: { _controller: OlitazHomeBundle:Presentation:development }

# ContactController
OlitazHomeBundle_contact:
    pattern:  /contact
    defaults: { _controller: OlitazHomeBundle:Contact:index }
OlitazHomeBundle_createContact:
    pattern:  /create_contact
    defaults: { _controller: OlitazHomeBundle:Contact:create }
OlitazHomeBundle_contacted:
    pattern:  /contacted
    defaults: { _controller: OlitazHomeBundle:Contact:contacted }
